[package]
name = "harness"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axstd = { path = "../../../ulib/axstd" }
ruxos_posix_api = { path = "../../../api/ruxos_posix_api", features = ["fs"] }
km-harness = { git = "https://github.com/LJxTHUCS/km-harness.git" }
km-command = { path = "../../../../../../framework/km-command", features = ["harness", "postcard"] }
log = "0.4"